name: Style_Check

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry via pip
      run: |
        python -m pip install --upgrade pip
        pip install poetry==2.1.2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ runner.os }}-

    - name: Validate lock file
      run: |
        poetry lock 

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Run Ruff
      run: poetry run ruff check .

    - name: Run Isort
      run: poetry run isort . --check-only
